// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IVoteVerifier
 * @notice Interface for the ZK-PLONK ballot verifier.
 *
 * The concrete implementation is generated by Circom + snarkjs from the
 * vote.circom circuit (see /circuits/vote.circom). Drop the generated
 * Verifier.sol into this slot — this interface ensures the voting contract
 * never needs to know the proof system internals.
 *
 * What the ZK proof guarantees:
 *   1. The voter holds a valid civic identity NFT (XRPL commitment)
 *   2. The voter has not already cast a ballot in this proposal (nullifier)
 *   3. The credit spend is <= their allocated voice credits
 *   4. The quadratic cost equation holds: credits_spent == votes_cast^2
 *   5. The vote direction is valid (support / against / abstain)
 *
 * None of the above reveals WHO voted or HOW they voted.
 */
interface IVoteVerifier {
    /**
     * @notice Verifies a ZK ballot proof.
     * @param proof      The PLONK proof bytes (generated client-side)
     * @param publicInputs Array of public inputs:
     *   [0] proposalId       — which proposal this ballot is for
     *   [1] nullifierHash    — prevents double-voting (unique per voter+proposal)
     *   [2] voteCommitment   — blinded vote direction commitment
     *   [3] creditsSpent     — number of voice credits consumed (public)
     *   [4] identityRoot     — merkle root of valid identity set
     * @return valid True if proof is valid
     */
    function verifyProof(
        bytes calldata proof,
        uint256[5] calldata publicInputs
    ) external view returns (bool valid);
}
